### ISSUE TITLE
Development of provider

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terraform-provider-terrakube#26]
Hi, 

I was wondering the development activities for the Terrakube terraform provider are not really active the last few months.
Is the provider going to be developed any further and if so are there any milestones? 

It would be of course awesome if we could also deploy organizations and workspaces through Terraform with this provider 😄 

Kind regards, 

Take

**Comment by ofbjansen** [comment]
@alfespa17 : I see you have added the organisation resource in the provider and readme file, but it is not yet pushed into the terraform registry. I noted that the tag has not changed for this and probably the new version is not being seen by the registry.

Or........are you working on other resources in this provider????? (That would be awesome 🥇 )

**Comment by alfespa17** [comment]
> @alfespa17 : I see you have added the organisation resource in the provider and readme file, but it is not yet pushed into the terraform registry. I noted that the tag has not changed for this and probably the new version is not being seen by the registry.
> 
> Or........are you working on other resources in this provider????? (That would be awesome 🥇 )

I will add some of the missing terrakube resources, I got some free time today. For example I will add a resource to create workspaces for the cli driven workflow.

**Comment by ofbjansen** [comment]
> > @alfespa17 : I see you have added the organisation resource in the provider and readme file, but it is not yet pushed into the terraform registry. I noted that the tag has not changed for this and probably the new version is not being seen by the registry.
> > Or........are you working on other resources in this provider????? (That would be awesome 🥇 )
> 
> I will add some of the missing terrakube resources, I got some free time today. For example I will add a resource to create workspaces for the cli driven workflow. Once I added a few resources I will create a new tag

Appreciate your time and effort on this. I will keep an eye out on the next tag. Thanks.

**Comment by alfespa17** [comment]
I added the resource to create org, workspace (cli drive workflow) and workspace variables, you can see the release notes here

https://github.com/AzBuilder/terraform-provider-terrakube/releases/tag/v0.3.0

I will try to add some more resources/datasource during the week, feel free to test any feedback is welcome.

**Comment by iam-take** [comment]
Thanks! You are a hero. I am testing the provider now. I will create separate issue's here for the ones that I find during my testing

**Comment by alfespa17** [comment]
I am closing this issue I already added some missing resources in version 0.3.0 and 0.4.0  I will add more the following week
