### ISSUE TITLE
`execution_mode` removed from organization API breaking terraform resource

### ISSUE THREAD

**Issue by hfeixas** [AzBuilder/terraform-provider-terrakube#34]
It appears execution_mode param has been removed from the API, however the terraform provider resource `terrakube_organization` still requires it:

Without Parameter:

```hcl
resource "terrakube_organization" "test" {
  name           = "MyOrg"
  description    = "My Org Description"
}
```

```
│ Error: Missing required argument
│ 
│   on main.tf line 32, in resource "terrakube_organization" "test":
│   32: resource "terrakube_organization" "test" {
│ 
│ The argument "execution_mode" is required, but no definition was found.
```

With Parameter:

```hcl
resource "terrakube_organization" "test" {
  name           = "MyOrg"
  description    = "My Org Description"
  execution_mode = "local"
}
```

```
│ Error: Error unmarshal payload response
│ 
│   with terrakube_organization.test,
│   on main.tf line 32, in resource "terrakube_organization" "test":
│   32: resource "terrakube_organization" "test" {
│ 
│ Error unmarshal payload response: data is not a jsonapi representation of '*client.OrganizationEntity'
```

**Comment by alfespa17** [comment]
Execution mode in the organization settings was added in Terrakube v2.20.0 as you can see in the release notes

https://github.com/orgs/AzBuilder/discussions/786

What terrakube version are you using?

**Comment by hfeixas** [comment]
Version 2.21.0-beta4

**Comment by alfespa17** [comment]
I will have to do some debugging I will update the issue one I found the issue

**Comment by alfespa17** [comment]
I think there was an issue when the provider was deleting the org, you can test with version 0.4.1 it should work now just make sure to use an organization name that is not in the database
