### ISSUE TITLE
Support VCS workspace type

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terraform-provider-terrakube#41]
With a quick looks, it seems we can refactor the existing `terrakube_worksapce_cli` resource to support VCS type?

**Comment by alfespa17** [comment]
Hello @stanleyz, that is correct the cli workspace is a special case for the workspace in terrakube but with some refactor with some small changes that could be use to create the vcs type, I can try to add it in the following days but if you would like to contribute all help and pull request are welcome.

**Comment by stanleyz** [comment]
Thanks for the prompt response @alfespa17 , love it.
