### ISSUE TITLE
Add support of setting template to workspace_vcs resource

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terraform-provider-terrakube#47]
Can we please add support of setting `Default template when doing a git push to the repository` to `terrakube_workspace_vcs` type? Thanks.

**Comment by stanleyz** [comment]
do you want to pick this up @alfespa17 ?  otherwise I'll raise a PR today

**Comment by alfespa17** [comment]
I can assign the issue to you if you want to help with this feature
