### ISSUE TITLE
Add Resource to manage schedules

### ISSUE THREAD

**Issue by ehuizar1028** [AzBuilder/terraform-provider-terrakube#65]
We have a monorepo setup of many states in folders, we would like to dynamically create the VCS projects per folder, which is possible currently.

But we would also like to create a schedule for drift detection, which is not possible with the provider since theres no `schedule` resource.

**Comment by alfespa17** [comment]
If anyone would like to help with this issue, this will require to implement the API called that is explained here.

https://docs.terrakube.io/api/methods/schedule

And the cron expression is using quartz notation as shown here.

https://freeformatter.com/cron-expression-generator-quartz.html

**Comment by ehuizar1028** [comment]
i can possibly implement this if i can find time. We do need it if we are going to productionize terrakube in our environment, so I'll submit a PR if i get time to implement it

I am currently getting around this with a simple curl request using `local-exec`

**Comment by BenjaminDecreusefond** [comment]
Hi @ehuizar1028 !

Did you have time to implement the PR ?

**Comment by alfespa17** [comment]
Support added here

https://github.com/AzBuilder/terraform-provider-terrakube/releases/tag/v0.8.0

**Comment by BenjaminDecreusefond** [comment]
Cool thanks !
