### ISSUE TITLE
import workspaces

### ISSUE THREAD

**Issue by KamranBiglari** [AzBuilder/terraform-provider-terrakube#69]
I recently migrated 500 workspaces from Terraform Cloud to Terrakube. Now that all the workspaces are in Terrakube, I want to import them into my Terraform configuration files to manage them through Terraform.

Firstly I used tfe provider but it's not compatible with terrakube
```
 provider "tfe" {
   alias    = "terrakube"
   hostname = "terrakube:8080"
   token    = var.TERRAKUBE_API_TOKEN
}
``` 

I switched to terrakube provider. 
How can I import `terrakube_workspace_cli` ?

```
terraform import terrakube_workspace_cli orgId,workspaceId

terraform import terrakube_workspace_cli.terrakube_workspace[\"github-library-eu-west-2\"] a3667a22-aa12-4257-8d56-11ee42527bcd,9687e81e-8ef2-4bf9-8d84-3f2ff9d9f33c

│ Error: Error unmarshal payload response
│
│ Error unmarshal payload response: data is not a jsonapi representation of '*client.WorkspaceEntity'
```

**Comment by alfespa17** [comment]
This https://github.com/AzBuilder/terraform-provider-terrakube/pull/66 added support to do the import, maybe you can try using [v0.7.0](https://github.com/AzBuilder/terraform-provider-terrakube/releases/tag/v0.7.0), that version include the that feature
