### ISSUE TITLE
Issue when deleting from UI and re-applying in cli

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terraform-provider-terrakube#72]
Hi ! 

I've been trying out the terraform provider to provision resources on my Terrakube instance and I think I found an unexpected behavior that seems strange to me. 

I created a workspace using Tofu, so far no issue everything went well. I then tried to delete the workspace from the UI and then re-apply stage and I got the following errors
```
data.tls_certificate.terrakube_certificate: Reading...
module.workspace_dummy.data.terrakube_organization.org: Reading...
data.tls_certificate.terrakube_certificate: Read complete after 0s [id=7c0092494f2484b871ff65f4516ee8efab75d924]
aws_iam_openid_connect_provider.terrakube_provider: Refreshing state... [id=arn:aws:iam::137068252831:oidc-provider/terrakube-api.command.weezevent.tech]
module.workspace_dummy.aws_iam_policy.terrakube_policy: Refreshing state... [id=arn:aws:iam::137068252831:policy/terrakube-policy-ultimate_test-staging]
module.workspace_dummy.data.terrakube_organization.org: Read complete after 0s [id=aa829267-11b6-4d38-9dd6-46a27352e155]
module.workspace_dummy.terrakube_workspace_cli.dynamic_credentials_workspace: Refreshing state... [id=b6331725-b0c9-49b0-a8b4-ad336a8b878b]
module.workspace_dummy.aws_iam_role.terrakube_role: Refreshing state... [id=terrakube-role-ultimate_test-staging]
module.workspace_dummy.aws_iam_role_policy_attachment.terrakube_policy_attachment: Refreshing state... [id=terrakube-role-ultimate_test-staging-20241010150322674300000001]

Planning failed. OpenTofu encountered an error while generating this plan.
╵
╷
│ Error: Error unmarshal payload response
│ 
│   with module.workspace_dummy.terrakube_workspace_cli.dynamic_credentials_workspace,
│   on ../../modules/workspaces/main.tf line 51, in resource "terrakube_workspace_cli" "dynamic_credentials_workspace":
│   51: resource "terrakube_workspace_cli" "dynamic_credentials_workspace" {
│ 
│ Error unmarshal payload response: data is not a jsonapi representation of '*client.WorkspaceEntity'
```

I don't know if this is expected behavior or not ?

**Comment by alfespa17** [comment]
You mentioned that you delete the workspace from the UI, if you create a workspace using terraform you should delete it using terraform not from the UI, I guess what is happening is that the workspace is still inside the state and the refreshing state operation is failing because the workspace does not longer exist.

**Comment by BenjaminDecreusefond** [comment]
Yep but to me this seems like an issue because I can say that I am not going to modify from the UI but at a company level I can't force people to modify it from the terraform directly. It will happen at some point and the terraform will be complicated to manage in that situation I think
