### ISSUE TITLE
Cannot use terraform to create a schedule and attach a template to a workspace

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terraform-provider-terrakube#74]
Hi ! 

I've been browsing the Terrakube provider documentation and I didn't see any way to create a schedule and attach a template with it to a workspace. Has this to be done necessarily from the UI ?

Also I was wondering, concerning our previous discussion about workspace management through terraform. It seems like the provider does not refresh state with the Terrakube API to detect any change between configuration and current state. It is planned to add the refresh ? Because it is quite complicated to work with the provider at a company as we are many, people will often perform change through the UI to test or just because they don't know terraform. Hence, the state becomes broken quite often :/ 

I understand if it's not your priority.

Regards!
Benjamin

**Comment by alfespa17** [comment]
Hello @BenjaminDecreusefond there is an open issue related to workspace shedules [here](https://github.com/AzBuilder/terraform-provider-terrakube/issues/65)

The provider refreshes the state for the resources, and it will detect changes every time you are running terraform/tofu so if you do changes from the UI once you run a `terraform/tofu plan/apply` from the CLI you should be able to see those.

**Comment by alfespa17** [comment]
Fixed in #76
