### ISSUE TITLE
Any plans on supporting Variable Sets?

### ISSUE THREAD

**Issue by bateller** [AzBuilder/terraform-provider-terrakube#75]
Hello 👋 
Is there any plan to support the concept of Variable Sets like TFE/TFC?
https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable_set

It would make handling multiple groups of variables across workspaces easier than using the or [workspace](https://registry.terraform.io/providers/AzBuilder/terrakube/latest/docs/resources/workspace_variable) variable resources as currently implemented, or having to use  [organization](https://registry.terraform.io/providers/AzBuilder/terrakube/latest/docs/resources/organization_variable) variables which requires setting up multiple organizations?

**Comment by alfespa17** [comment]
Hello @bateller there is one open issue related to that; we need to implement it first

https://github.com/AzBuilder/terrakube/issues/1146

**Comment by bateller** [comment]
Thank you. Can't believe I missed it. 🤦
