### ISSUE TITLE
Provider missing support for module creation with tag_prefix and path to module

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terraform-provider-terrakube#77]
Hi ! 

We are now set up with modules and we would like to terraform them in order to avoid doing manually. However, we figured out that the provider does not implement the `tag_prefix` and the `path` parameters that we find in the UI. We tried to find a way to implement it ourselves and then create a PR but we struggle even finding if the API endpoints are implemented. 

Would you have any clue for us please ? 

regards

**Comment by alfespa17** [comment]
Hello @BenjaminDecreusefond you could check the UI source code here:

https://github.com/AzBuilder/terrakube/blob/5639fec67c1a16d95fac56e0e499d01b8ca3a8a2/ui/src/domain/Modules/Create.jsx#L131

You can add the missing pieces here for the module creation logic:

https://github.com/AzBuilder/terraform-provider-terrakube/blob/b4669fedbb6237be89a6a5832ca2d7405896ef18/internal/provider/module_resource.go#L52

**Comment by alfespa17** [comment]
You can also check the open api specification in this endpoint

![image](https://github.com/user-attachments/assets/a5ed2ae7-1f97-4745-9e5e-086e2d2181bf)

**Comment by BenjaminDecreusefond** [comment]
Hi @alfespa17,

I'm unable to push on any branch or PR, what is the way to do ?

**Comment by alfespa17** [comment]
> Hi @alfespa17,
> 
> I'm unable to push on any branch or PR, what is the way to do ?

You need to create a fork, and create the PR from your fork to this repo

**Comment by BenjaminDecreusefond** [comment]
Okay, thanks !
