### ISSUE TITLE
Missing job type when provisioning workspace_schedule

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terraform-provider-terrakube#82]
Hi ! 

I tried to provision a workspace schedule from the provider. The creation of the resource works well however, when we look on the UI we see this:
![Screenshot 2024-10-25 at 09 54 15](https://github.com/user-attachments/assets/9d41a6d8-26ea-45e0-80d9-de3467531041)
It seems like there is no job type attached to the schedule and therefore after testing tonight, it appears that no job was triggered at all. The creation of the resource seems fine tho
```
OpenTofu will perform the following actions:

  # terrakube_workspace_schedule.workspaces_schedule["test"] will be created
  + resource "terrakube_workspace_schedule" "workspaces_schedule" {
      + id           = (known after apply)
      + schedule     = "0 0 4 ? * * *"
      + template_id  = "9163e61b-b12e-4f72-a3f5-5eb5918baaa6"
      + workspace_id = "5b58f17d-d440-4a4e-af40-bcdf895cd1ca"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

terrakube_workspace_schedule.workspaces_schedule["test"]: Creating...
terrakube_workspace_schedule.workspaces_schedule["test"]: Creation complete after 1s [id=4a0c7407-7f1a-48ef-8865-faee55fcb80b]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by BenjaminDecreusefond** [comment]
Maybe it is due to the fact that the body request is not implementing the good body params ? I see here
https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/rs/workspace/schedule/Schedule.java#L42
that the body param is template_reference
and here that we use another jsonapi param
https://github.com/AzBuilder/terraform-provider-terrakube/blob/main/internal/client/client.go#L133

**Comment by alfespa17** [comment]
You are correct it is using the wrong property I will fix it later today

**Comment by BenjaminDecreusefond** [comment]
Thanks !

**Comment by BenjaminDecreusefond** [comment]
I could test and it's now working !
