### ISSUE TITLE
Issues with workspace destroy and creation of VCS

### ISSUE THREAD

**Issue by BenjaminDecreusefond** [AzBuilder/terraform-provider-terrakube#85]
Hi !

I think there is an issue with the workspace destroy on the provider. If we create a workspace through the provider and add variables to it then when we destroy it, it seems like the workspace is destroyed before the variables and then the provider is unable to destroy the variables as they are buggy and not attached to any workspace.

Steps to reproduce:
- Create a workspace with variables attached to it
- Change a parameter in the code that will force to recreate the workspace and it should bug with 

```
╷
│ Error: Error unmarshal payload response
│ 
│   with module.workspace["eurostar"].terrakube_workspace_vcs.workspace,
│   on .terraform/modules/workspace/main.tf line 1, in resource "terrakube_workspace_vcs" "workspace":
│    1: resource "terrakube_workspace_vcs" "workspace" {
│ 
│ Error unmarshal payload response, response status: 500 Internal Server Error, response body: {%!s(*http.http2clientStream=&{0x1400023d800 0x1400018a010 <nil> <nil>
│ 3 {{0 0} {{} 0x14000400330 {0 0 0 <nil> <nil>} 1374393729896} <nil> 0 0x14000184110 <nil> <nil> <nil>} true false {0 {0 0}} 0x1400059a060 <nil> 0x1400059a000
│ 0x1400059a120 <nil> 0x1400059a0c0 0x140000f2cf0 {[] 65133 0x1400023d860} {[] 4194137 0x1400023d870} -1 <nil> 0x14000579320 403 true true true true true false 0
│ true false map[] 0x140000f2d68})}, error: data is not a jsonapi representation of '*client.WorkspaceEntity'
╵

```

# Expected behavior
Variables destroyed before the workspace 

# Second issue while creating VCS workspace through provider

I also tried to provision VCS workspace using the terraform provider and I encountered the following issue:
It seems like the providers create a half VCS and half CLI workspace. For instance here
![Screenshot 2024-10-29 at 12 07 52](https://github.com/user-attachments/assets/c8354260-c093-4124-8a4c-ca6ed38e87a8)
There is the github link as if it is a VCS workspace however, here:
![Screenshot 2024-10-29 at 12 08 36](https://github.com/user-attachments/assets/2593afca-1cdc-410c-bc1c-ca2091d893d3)
I don't have the ability to add webhook as for VCS workspaces. I think the provider is missing the relationship property when creating the workspace no ?
I have to admit it's tough one to fix and I don't know how to 😅

**Comment by alfespa17** [comment]
Hello @BenjaminDecreusefond 

```
I also tried to provision VCS workspace using the terraform provider and I encountered the following issue:
It seems like the providers create a half VCS and half CLI workspace. For instance here
```
What do you mean with half VCS and half CLI??? the 2 types are shown differently.

![image](https://github.com/user-attachments/assets/38ebeaf8-d1d3-4b7b-beda-88b58f45dbc7)


```
I don't have the ability to add webhook as for VCS workspaces. I think the provider is missing the relationship property when creating the workspace no ?
```

To clarify the VCS and CLI driven workflow behave different, the CLI driven workflow is not connected to any git repository so you dont have to create a webhook for those.

You can read this.

https://developer.hashicorp.com/terraform/cloud-docs/run/ui
https://developer.hashicorp.com/terraform/cloud-docs/run/cli
