### ISSUE TITLE
Issue with terrakube_team name attribute on import

### ISSUE THREAD

**Issue by fishfacemcgee** [AzBuilder/terraform-provider-terrakube#92]
I created a team in the Terrakube UI, and then went to import it. It had shown the name as changing (going from unset to the value I set, despite it matching what is in the UI) and upon completing apply, I get this error:

```
���
��� Error: Provider produced inconsistent result after apply
��� 
��� When applying changes to terrakube_team.example, provider
��� "provider[\"registry.terraform.io/azbuilder/terrakube\"]" produced an
��� unexpected new value: .name: was cty.StringVal("test@example.com"), but
��� now cty.StringVal("").
��� 
��� This is a bug in the provider, which should be reported in the provider's
��� own issue tracker.
���
```

This situation (proposed change from unset to the email) is now happening continuously. Adding a `ignore_changes` block for the name attribute successfully works around this.

**Comment by alfespa17** [comment]
The import is only taking the IDs

https://github.com/AzBuilder/terraform-provider-terrakube/blob/05331f30563adf61cf3939cc3114bb0b91ec7394/internal/provider/team_resource.go#L412

I guess when terraform is reading the team here, the name field is missing in this block

https://github.com/AzBuilder/terraform-provider-terrakube/blob/05331f30563adf61cf3939cc3114bb0b91ec7394/internal/provider/team_resource.go#L274

**Comment by alfespa17** [comment]
Do you want to help with the fix?

**Comment by fishfacemcgee** [comment]
Not sure if it changes the potential scope of the issue, but it looks like the initial apply post-import actually ended up wiping the email address from the team.

<img width="365" alt="Screenshot 2024-12-20 at 12 44 12 PM" src="https://github.com/user-attachments/assets/a5dbcea7-c462-447b-8848-94e47b551f9b" />

I'm not especially familiar with provider internals, but that makes me think that there's more going on here than just an issue on read/import as I would expect it to just override the empty-read value with the new value, but that doesn't appear to have happened.

Is maybe part of the issue that the name is being read from State instead of Plan inside of `Update`?

https://github.com/AzBuilder/terraform-provider-terrakube/blob/05331f30563adf61cf3939cc3114bb0b91ec7394/internal/provider/team_resource.go#L313

If the intent is that the email isn't expected to change, would it be better to read from Plan and then include the requiresReplace modifier?

> Do you want to help with the fix?

I think I'll have some time to take a look at it later today. I haven't touched TF providers much before, though.

**Comment by alfespa17** [comment]
Yeah you are right the update should take the value from the plan not the state, and in your case the state only has the ID that is why it was override as empty when you ran the apply
